# Site settings
title: Frejas Konfirmation
subtitle: Fredag d. 17. Maj 2019
email: freja.bruskin@gmail.com
description: Siden om Frejas konfirmation, Fredag d. 17. Maj 2019 på Låsby kro 
#baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site
author: Freja Bruskin
street_address: Bredsig 17
city: Sorring
state: TN
zip_code: 8641
country: Danmark
phone: 50 90 15 76

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
